- platform: gpio # Button:
  pin:
    number: GPIO42
    inverted: True
  id: button_main
- platform: template
  id: have_update
  filters:
    - settle: 1000ms
  on_release:
    - if:
        condition:
          lambda: return !id(is_off);
        then:
          - lvgl.arc.update:
              id: arc_thermostat
              value: !lambda return (id(climate_target_temperature).state*2);
          - binary_sensor.template.publish:
              id: need_catchup
              state: false
    - lvgl.widget.focus:
        id: arc_thermostat
        freeze: true
        editing: true
- platform: template
  id: need_catchup